if(EXISTS "/home/startrack/StarTrack/debug-build-startrack/StarTrack_tests[1]_tests.cmake")
  include("/home/startrack/StarTrack/debug-build-startrack/StarTrack_tests[1]_tests.cmake")
else()
  add_test(StarTrack_tests_NOT_BUILT StarTrack_tests_NOT_BUILT)
endif()
